{
 "title": "Power_prediction_Ambattur",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Power production in Ambattur",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT *\r\nFROM prediction_amb.power_prediction\r\nWHERE ghi <> 0 AND power <> 0;"
    }
   ]
  },
  {
   "title": "Total no. of entries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \r\n  COUNT(*) AS total_entries\r\nFROM \r\n  prediction_amb.power_prediction\r\nWHERE \r\n  $__timeFilter(time_updated)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Power-GHI-Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(time_updated) AS time_sec,\r\n  Power, GHI, Temperature\r\nFROM\r\n  prediction_amb.power_prediction\r\nWHERE\r\n  time_updated BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY\r\n  time_updated ASC\r\n\r\n"
    }
   ]
  },
  {
   "title": "Recent stats",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT Temperature, GHI, power, time_updated\r\nFROM prediction_amb.power_prediction\r\nORDER BY time_updated DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Comparison of GHI vs Power(scaled)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  DATE_FORMAT(time_updated, '%Y-%m-%d %H:00:00') AS time_interval,\r\n  (AVG(GHI) - min_max_values.min_ghi) / (min_max_values.max_ghi - min_max_values.min_ghi) AS scaled_ghi,\r\n  (AVG(power) - min_max_values.min_power) / (min_max_values.max_power - min_max_values.min_power) AS scaled_power\r\nFROM\r\n  prediction_amb.power_prediction,\r\n  (SELECT \r\n      MIN(GHI) AS min_ghi, \r\n      MAX(GHI) AS max_ghi, \r\n      MIN(power) AS min_power, \r\n      MAX(power) AS max_power\r\n   FROM \r\n      prediction_amb.power_prediction) AS min_max_values\r\nWHERE\r\n  $__timeFilter(time_updated)\r\nGROUP BY\r\n  UNIX_TIMESTAMP(time_updated) DIV (2 * 60 * 60)\r\nORDER BY\r\n  time_interval ASC;\r\n"
    }
   ]
  },
  {
   "title": "Power production over the day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  time_updated AS time,\r\n  Power\r\nFROM\r\n  prediction_amb.power_prediction\r\nWHERE\r\n  $__timeFilter(time_updated)\r\nORDER BY\r\n  time_updated ASC\r\n\r\n"
    }
   ]
  },
  {
   "title": "Average Power-GHI-Temperature produced in every 30 mins ",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \r\n    DATE_FORMAT(time_updated, '%Y-%m-%d %H:%i') AS time_interval,\r\n    AVG(power) AS avg_power,\r\n    AVG(ghi) AS avg_ghi,\r\n    AVG(temperature) AS avg_temperature\r\nFROM \r\n    prediction_amb.power_prediction\r\nWHERE \r\n    time_updated >= DATE_SUB(NOW(), INTERVAL 1 DAY)  -- Adjust as needed for your time range\r\nGROUP BY \r\n    UNIX_TIMESTAMP(time_updated) DIV (30 * 60)\r\nORDER BY \r\n    time_interval ASC;\r\n"
    }
   ]
  },
  {
   "title": "Statistics of GHI and Power",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  AVG(GHI) AS avg_ghi,\r\n  STDDEV(GHI) AS stddev_ghi,\r\n  VARIANCE(GHI) AS variance_ghi,\r\n  AVG(power) AS avg_power,\r\n  STDDEV(power) AS stddev_power,\r\n  VARIANCE(power) AS variance_power\r\nFROM\r\n  prediction_amb.power_prediction\r\nWHERE\r\n  $__timeFilter(time_updated)\r\n"
    }
   ]
  },
  {
   "title": "GeoMap - Ambattur",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  13.106279 AS latitude,\r\n  80.169897 AS longitude,\r\n  power,\r\n  GHI,\r\n  temperature,\r\n  time_updated\r\nFROM\r\n  prediction_amb.power_prediction\r\nWHERE\r\n  $__timeFilter(time_updated)\r\nORDER BY\r\n  time_updated DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Temperature stats in the range of 30-39 ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN temperature >= 0 AND temperature < 10 THEN '0-9'\r\n    WHEN temperature >= 10 AND temperature < 20 THEN '10-19'\r\n    WHEN temperature >= 20 AND temperature < 30 THEN '20-29'\r\n    WHEN temperature >= 30 AND temperature < 40 THEN '30-39'\r\n    WHEN temperature >= 40 AND temperature < 50 THEN '40-49'\r\n    -- Add more ranges as necessary\r\n    ELSE '50+'\r\n  END AS temperature_range,\r\n  COUNT(*) AS count,\r\n  AVG(temperature) AS avg_temperature,\r\n  MIN(temperature) AS min_temperature,\r\n  MAX(temperature) AS max_temperature\r\nFROM\r\n  prediction_amb.power_prediction\r\nWHERE\r\n  $__timeFilter(time_updated)\r\nGROUP BY\r\n  temperature_range\r\nORDER BY\r\n  temperature_range;\r\n"
    }
   ]
  },
  {
   "title": "Power produced at different timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  time_updated,\r\n  power\r\nFROM\r\n  prediction_amb.power_prediction\r\nWHERE\r\n  TIME(time_updated) BETWEEN '13:00:00' AND '17:00:00'\r\n  AND DATE(time_updated) = CURDATE()  -- Optional: Ensure it's today's date if needed\r\nORDER BY\r\n  time_updated ASC;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Proportion of Power in ranges of 1000",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN power >= 0 AND power < 1000 THEN '0-999'\r\n    WHEN power >= 1000 AND power < 2000 THEN '1000-1999'\r\n    WHEN power >= 2000 AND power < 3000 THEN '2000-2999'\r\n    WHEN power >= 3000 AND power < 4000 THEN '3000-3999'\r\n    WHEN power >= 4000 AND power < 5000 THEN '4000-4999'\r\n    -- Add more ranges as necessary\r\n    ELSE '5000+'\r\n  END AS power_range,\r\n  COUNT(*) AS count\r\nFROM\r\n  prediction_amb.power_prediction\r\nWHERE\r\n  $__timeFilter(time_updated)\r\nGROUP BY\r\n  power_range\r\nORDER BY\r\n  power_range;\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  MAX(temperature) AS max_temperature,\r\n  MAX(GHI) AS max_ghi,\r\n  MAX(power) AS max_power\r\nFROM\r\n  prediction_amb.power_prediction\r\nWHERE\r\n  DATE(time_updated) = CURDATE();\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  time_updated,\r\n  power\r\nFROM\r\n  prediction_amb.power_prediction\r\nWHERE\r\n  time_updated >= NOW() - INTERVAL 1 HOUR\r\nORDER BY\r\n  time_updated ASC\r\n"
    }
   ]
  },
  {
   "title": "Proportion of GHI in ranges of 100",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  CONCAT(FLOOR(GHI / 100) * 100, ' - ', FLOOR(GHI / 100) * 100 + 99) AS ghi_range,\r\n  COUNT(*) AS count\r\nFROM\r\n  prediction_amb.power_prediction\r\nGROUP BY\r\n  FLOOR(GHI / 100)\r\nORDER BY\r\n  ghi_range ASC;\r\n"
    }
   ]
  }
 ]
}